version: '3'

services:
  db:

    container_name: tracker
    image: postgis/postgis
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432


  web:
    build:
      context: .
    command: gunicorn geo.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  django-backgroudtask:
    build:
      context: .
    command: python manage.py process_tasks
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - web


volumes:
  db_data:
