# Generated by Django 3.0.5 on 2020-06-12 07:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongestRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('route_date', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'longest_route',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinates', django.contrib.gis.db.models.fields.LineStringField(blank=True, srid=4326)),
                ('cached_distance', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['-cached_distance'], name='tracker_rou_cached__1c4373_idx'),
        ),
        migrations.AddField(
            model_name='longestroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Route'),
        ),
    ]
